; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:adafruit_qtpy_esp32c3]
platform = espressif32 @ 6.8.1
board = adafruit_qtpy_esp32c3
framework = arduino
;monitor_port = /dev/cu.usbmodem83201
;upload_port = /dev/cu.usbmodem83201
lib_deps =
  https://github.com/MagdiLaoun/MLTMC.git
  https://github.com/MagdiLaoun/MLEncoder.git
  https://github.com/MagdiLaoun/MLSpeed.git
